[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project.urls]
"Homepage" = "https://github.com/letruxux/coralmc"
"Bug Tracker" = "https://github.com/letruxux/coralmc/issues"
"JS/TS Version" = "https://github.com/gigantino/coralmc"
